name: spark-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - pandas-datareader
  - pytables
  - scikit-learn
  - scikit-image 
  - pip:
    - python-snappy
    - fastparquet
    - azureml-mlflow
    - pyspark
